apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
  namespace: gameai-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '5000'
    spec:
      containers:
      - name: gateway-api
        image: gameai/gateway-api:dev
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Docker"
        - name: DOTNET_USE_POLLING_FILE_WATCHER
          value: "true"
        envFrom:
        - configMapRef:
            name: gameai-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  namespace: gameai-dev
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '5000'
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: gateway-api