apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-api
  namespace: gameai-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-api
  template:
    metadata:
      labels:
        app: project-api
    spec:
      containers:
      - name: project-api
        image: gameai/project-api:dev
        ports:
        - containerPort: 5001
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5001"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Docker"
        - name: DOTNET_USE_POLLING_FILE_WATCHER
          value: "true"
        envFrom:
        - configMapRef:
            name: gameai-config
---
apiVersion: v1
kind: Service
metadata:
  name: project-api
  namespace: gameai-dev
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: project-api