apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: gameai-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: gameai-secrets-dev
              key: rabbit-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: gameai-secrets-dev
              key: rabbit-password
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: gameai-dev
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: http
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
