FROM mcr.microsoft.com/dotnet/sdk:9.0 AS development
WORKDIR /src

ENV PROJECT_NAME=Gateway
ENV SHARED_PROJECT_NAME=Shared

ENV ASPNETCORE_ENVIRONMENT=Docker
ENV ASPNETCORE_URLS=http://+:5000
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 5000

# Copy project files (context is now services folder)
COPY ["${PROJECT_NAME}/${PROJECT_NAME}.csproj", "${PROJECT_NAME}/"]
COPY ["${SHARED_PROJECT_NAME}/${SHARED_PROJECT_NAME}.csproj", "${SHARED_PROJECT_NAME}/"]

RUN dotnet restore "${PROJECT_NAME}/${PROJECT_NAME}.csproj"

# Copy source code
COPY ${PROJECT_NAME}/. ${PROJECT_NAME}/
COPY ${SHARED_PROJECT_NAME}/. ${SHARED_PROJECT_NAME}/

ENTRYPOINT dotnet watch run --project ${PROJECT_NAME} --no-launch-profile