apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-api
  namespace: gameai-prod
  labels:
    app.kubernetes.io/name: project-api
    app.kubernetes.io/component: microservice
    app.kubernetes.io/version: "1.0.0"
    environment: production
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: project-api
      app.kubernetes.io/component: microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: project-api
        app.kubernetes.io/component: microservice
        app.kubernetes.io/version: "1.0.0"
        environment: production
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '5001'
        co.elastic.logs/enabled: 'true'
        co.elastic.logs/json.keys_under_root: 'true'
    spec:
      serviceAccountName: gameai-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - project-api
              topologyKey: kubernetes.io/hostname
      # topologySpreadConstraints:
      # - maxSkew: 1
      #   topologyKey: topology.kubernetes.io/zone
      #   whenUnsatisfiable: DoNotSchedule
      #   labelSelector:
      #     matchLabels:
      #       app.kubernetes.io/name: project-api
      containers:
      - name: project-api
        image: genwatt/project-api:latest  # Use specific version, not latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5001
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
        # envFrom:
        # - configMapRef:
        #     name: gameai-config-prod
        # - secretRef:
        #     name: gameai-secrets
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: gameai-config-prod
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: gameai-config-prod
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: gameai-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gameai-secrets
              key: postgres-password
        - name: Rabbit__Host
          valueFrom:
            configMapKeyRef:
              name: gameai-config-prod
              key: RABBIT__HOST
        - name: Rabbit__User
          valueFrom:
            secretKeyRef:
              name: gameai-secrets
              key: rabbit-user
        - name: Rabbit__Pass
          valueFrom:
            secretKeyRef:
              name: gameai-secrets
              key: rabbit-password
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-log
          mountPath: /var/log
        resources:
          requests:
            cpu: "100m"   
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /api/health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 30
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 1Gi
      - name: var-log
        emptyDir:
          sizeLimit: 1Gi
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: project-api
  namespace: gameai-prod
  labels:
    app.kubernetes.io/name: project-api
    app.kubernetes.io/component: microservice
    environment: production
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '5001'
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 5001
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: project-api
    app.kubernetes.io/component: microservice
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: project-api-hpa
  namespace: gameai-prod
  labels:
    app.kubernetes.io/name: project-api
    app.kubernetes.io/component: microservice
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: project-api-pdb
  namespace: gameai-prod
  labels:
    app.kubernetes.io/name: project-api
    app.kubernetes.io/component: microservice
    environment: production
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: project-api
      app.kubernetes.io/component: microservice