version: "3.8"
services:
  gateway-api:
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - project-api

  project-api:
    build:
      context: .
      dockerfile: Project.API/Dockerfile
    expose:
      - "5001"
