version: "3.8"

services:
  gateway-api:
    build:
      context: ./services
      dockerfile: SynapseStudio.Gateway/Dockerfile.dev
      target: development
    volumes:
      - ./services:/src
      - nuget_cache:/root/.nuget/packages
      - /src/SynapseStudio.Gateway/bin
      - /src/SynapseStudio.Gateway/obj
      - /src/SynapseStudio.Shared/bin
      - /src/SynapseStudio.Shared/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - "5000:5000"
    depends_on:
      - project-api
    networks:
      - gameai-network

  project-api:
    build:
      context: ./services
      dockerfile: SynapseStudio.ProjectService/Dockerfile.dev
      target: development
    volumes:
      - ./services:/src
      - nuget_cache:/root/.nuget/packages
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Api/bin
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Api/obj
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Application/bin
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Application/obj
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Core/bin
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Core/obj
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Domain/bin
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Domain/obj
      - /src/SynapseStudio.Shared/bin
      - /src/SynapseStudio.Shared/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    expose:
      - "5001"
    networks:
      - gameai-network

  conversation-api:
    build:
      context: ./services
      dockerfile: SynapseStudio.ConversationService/Dockerfile.dev
      target: development
    volumes:
      - ./services:/src
      - nuget_cache:/root/.nuget/packages
      - /src/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Api/bin
      - /src/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Api/obj
      - /src/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Application/bin
      - /src/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Application/obj
      - /src/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Core/bin
      - /src/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Core/obj
      - /src/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Domain/bin
      - /src/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Domain/obj
      - /src/SynapseStudio.Shared/bin
      - /src/SynapseStudio.Shared/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    expose:
      - "5002"
    networks:
      - gameai-network

volumes:
  nuget_cache:


networks:
  gameai-network:
    driver: bridge
