version: "3.8"

services:
  gateway-api:
    build:
      context: ./services
      dockerfile: Gateway/Dockerfile.dev
      target: development
    volumes:
      - ./services:/src
      - nuget_cache:/root/.nuget/packages
      - /src/Gateway/bin
      - /src/Gateway/obj
      - /src/Shared/bin
      - /src/Shared/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - "5000:5000"
    depends_on:
      - project-api
    networks:
      - gameai-network

  project-api:
    build:
      context: ./services
      dockerfile: ProjectService/Dockerfile.dev
      target: development
    volumes:
      - ./services:/src
      - nuget_cache:/root/.nuget/packages
      - /src/ProjectService/src/ProjectService.Api/bin
      - /src/ProjectService/src/ProjectService.Api/obj
      - /src/ProjectService/src/ProjectService.Application/bin
      - /src/ProjectService/src/ProjectService.Application/obj
      - /src/ProjectService/src/ProjectService.Core/bin
      - /src/ProjectService/src/ProjectService.Core/obj
      - /src/ProjectService/src/ProjectService.Domain/bin
      - /src/ProjectService/src/ProjectService.Domain/obj
      - /src/Shared/bin
      - /src/Shared/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    expose:
      - "5001"
    networks:
      - gameai-network

  conversation-api:
    build:
      context: ./services
      dockerfile: ConversationService/Dockerfile.dev
      target: development
    volumes:
      - ./services:/src
      - nuget_cache:/root/.nuget/packages
      - /src/ConversationService/src/ConversationService.Api/bin
      - /src/ConversationService/src/ConversationService.Api/obj
      - /src/ConversationService/src/ConversationService.Application/bin
      - /src/ConversationService/src/ConversationService.Application/obj
      - /src/ConversationService/src/ConversationService.Core/bin
      - /src/ConversationService/src/ConversationService.Core/obj
      - /src/ConversationService/src/ConversationService.Domain/bin
      - /src/ConversationService/src/ConversationService.Domain/obj
      - /src/Shared/bin
      - /src/Shared/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    expose:
      - "5002"
    networks:
      - gameai-network

volumes:
  nuget_cache:


networks:
  gameai-network:
    driver: bridge
