version: "3.8"

services:
  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-projectdb}
      POSTGRES_USER: ${POSTGRES_USER:-project}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-projectpwd}
    ports:
      - "5432:5432"
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
  gateway-api:
    build:
      context: .
      dockerfile: ./services/SynapseStudio.Gateway/Dockerfile.dev
      target: development
    volumes:
      - .:/src
      - nuget_cache:/root/.nuget/packages
      - /src/services/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Api/bin
      - /src/services/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Api/obj
      - /src/services/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Application/bin
      - /src/services/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Application/obj
      - /src/services/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Core/bin
      - /src/services/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Core/obj
      - /src/services/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Domain/bin
      - /src/services/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Domain/obj
      - /src/services/SynapseStudio.Shared/bin
      - /src/services/SynapseStudio.Shared/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - "5000:5000"
    depends_on:
      - project-api
    networks:
      - gameai-network

  project-api:
    build:
      context: .
      dockerfile: ./services/SynapseStudio.ProjectService/Dockerfile.dev
      target: development
    volumes:
      - .:/src
      - nuget_cache:/root/.nuget/packages
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Api/bin
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Api/obj
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Application/bin
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Application/obj
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Core/bin
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Core/obj
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Domain/bin
      - /src/SynapseStudio.ProjectService/src/SynapseStudio.ProjectService.Domain/obj
      - /src/SynapseStudio.Shared/bin
      - /src/SynapseStudio.Shared/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ConnectionStrings__ProjectDb=${PROJECT_DB_CONN:-Host=postgres;Port=5432;Database=projectdb;Username=${POSTGRES_USER:-project};Password=${POSTGRES_PASSWORD:-projectpwd}}
      - Rabbit__Host=${RABBITMQ_HOST:-rabbitmq}
      - Rabbit__User=${RABBITMQ_USER:-guest}
      - Rabbit__Pass=${RABBITMQ_PASS:-guest}
    expose:
      - "5001"
    networks:
      - gameai-network
    depends_on:
      - postgres
      - rabbitmq

  conversation-api:
    build:
      context: .
      dockerfile: ./services/SynapseStudio.ConversationService/Dockerfile.dev
      target: development
    volumes:
      - .:/src
      - nuget_cache:/root/.nuget/packages
      - /src/services/services/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Api/bin
      - /src/services/services/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Api/obj
      - /src/services/services/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Application/bin
      - /src/services/services/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Application/obj
      - /src/services/services/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Core/bin
      - /src/services/services/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Core/obj
      - /src/services/services/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Domain/bin
      - /src/services/services/SynapseStudio.ConversationService/src/SynapseStudio.ConversationService.Domain/obj
      - /src/services/services/SynapseStudio.Shared/bin
      - /src/services/services/SynapseStudio.Shared/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    expose:
      - "5002"
    networks:
      - gameai-network
    depends_on:
      - rabbitmq

volumes:
  nuget_cache:


networks:
  gameai-network:
    driver: bridge
