version: "3.8"

networks:
  gameai-network:
    driver: bridge

volumes:
  nuget_cache:
  pgdata:


services:
  postgres:
    image: postgres:16-alpine
    container_name: gameai-postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB:-projectdb}
      POSTGRES_USER: ${POSTGRES_USER:-project}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-projectpwd}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gameai-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gameai-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - gameai-network

  gateway-api:
    build:
      context: .
      dockerfile: services/SynapseStudio.Gateway/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - project-api
    networks:
      - gameai-network

  project-api:
    build:
      context: .
      dockerfile: services/SynapseStudio.ProjectService/Dockerfile
    expose:
      - "5001"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=projectdb
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=projectpwd
      - Rabbit__Host=rabbitmq
      - Rabbit__User=guest
      - Rabbit__Pass=guest
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - gameai-network

  conversation-api:
    build:
      context: .
      dockerfile: services/SynapseStudio.ConversationService/Dockerfile
    expose:
      - "5002"
    networks:
      - gameai-network
