apiVersion: v1
kind: Namespace
metadata:
  name: gameai-prod
  labels:
    name: gameai-prod
    environment: production
    app.kubernetes.io/name: gameai
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: "kubernetes.io/os=linux"
---
# Pod Security Standards - Restricted
apiVersion: v1
kind: LimitRange
metadata:
  name: gameai-prod-limits
  namespace: gameai-prod
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "2000m"
      memory: "2Gi"
    min:
      cpu: "10m"
      memory: "32Mi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gameai-prod-quota
  namespace: gameai-prod
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "10"