apiVersion: v1
kind: Namespace
metadata:
  name: gameai-prod
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gameai-prod-quota
  namespace: gameai-prod
spec:
  hard:
    pods: "100"
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: gameai-prod-limits
  namespace: gameai-prod
spec:
  limits:
    - type: Container
      max:
        cpu: "2"
        memory: 2Gi
      min:
        cpu: "100m"
        memory: 128Mi
      default:
        cpu: "500m"
        memory: 512Mi
      defaultRequest:
        cpu: "200m"
        memory: 256Mi