FROM mcr.microsoft.com/dotnet/sdk:9.0 AS development
WORKDIR /src

ENV API_PROJECT_NAME=ProjectService.Api
ENV APPLICATION_PROJECT_NAME=ProjectService.Application
ENV CORE_PROJECT_NAME=ProjectService.Core
ENV DOMAIN_PROJECT_NAME=ProjectService.Domain
ENV SHARED_PROJECT_NAME=Shared

ENV ASPNETCORE_ENVIRONMENT=Docker
ENV ASPNETCORE_URLS=http://+:5001
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 5001

# Copy project files (context is now services folder)
COPY ["ProjectService/src/${API_PROJECT_NAME}/${API_PROJECT_NAME}.csproj", "ProjectService/src/${API_PROJECT_NAME}/"]
COPY ["ProjectService/src/${APPLICATION_PROJECT_NAME}/${APPLICATION_PROJECT_NAME}.csproj", "ProjectService/src/${APPLICATION_PROJECT_NAME}/"]
COPY ["ProjectService/src/${CORE_PROJECT_NAME}/${CORE_PROJECT_NAME}.csproj", "ProjectService/src/${CORE_PROJECT_NAME}/"]
COPY ["ProjectService/src/${DOMAIN_PROJECT_NAME}/${DOMAIN_PROJECT_NAME}.csproj", "ProjectService/src/${DOMAIN_PROJECT_NAME}/"]
COPY ["${SHARED_PROJECT_NAME}/${SHARED_PROJECT_NAME}.csproj", "${SHARED_PROJECT_NAME}/"]

RUN dotnet restore "ProjectService/src/${API_PROJECT_NAME}/${API_PROJECT_NAME}.csproj"

# Copy source code
COPY ProjectService/. ProjectService/
COPY ${SHARED_PROJECT_NAME}/. ${SHARED_PROJECT_NAME}/

ENTRYPOINT dotnet watch run --project ProjectService/src/${API_PROJECT_NAME}/${API_PROJECT_NAME}.csproj --no-launch-profile