FROM mcr.microsoft.com/dotnet/sdk:9.0 AS development
WORKDIR /src

ENV PROJECT_NAME=SynapseStudio.Gateway
ENV SHARED_PROJECT_NAME=SynapseStudio.Shared

ENV ASPNETCORE_ENVIRONMENT=Docker
ENV ASPNETCORE_URLS=http://+:5000
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 5000

COPY ["services/${PROJECT_NAME}/${PROJECT_NAME}.csproj", "services/${PROJECT_NAME}/"]
COPY ["services/${SHARED_PROJECT_NAME}/**/*.csproj", "services/${SHARED_PROJECT_NAME}/"]

RUN dotnet restore "services/${PROJECT_NAME}/${PROJECT_NAME}.csproj"

COPY services/${PROJECT_NAME}/. services/${PROJECT_NAME}/
COPY services/${SHARED_PROJECT_NAME}/. services/${SHARED_PROJECT_NAME}/

CMD ["dotnet", "watch", "run", "--project", "services/SynapseStudio.Gateway/SynapseStudio.Gateway.csproj", "--no-launch-profile"]