FROM mcr.microsoft.com/dotnet/sdk:9.0 AS development
WORKDIR /src

ENV ASPNETCORE_ENVIRONMENT=Docker
ENV ASPNETCORE_URLS=http://+:5001
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 5001

# First restore packages for better caching
COPY ["Project.API/Project.API.csproj", "Project.API/"]
COPY ["GameAI.Shared/GameAI.Shared.csproj", "GameAI.Shared/"]
RUN dotnet restore "Project.API/Project.API.csproj"

ENTRYPOINT ["dotnet", "watch", "run", "--project", "Project.API", "--no-launch-profile"]